// @ts-check
import { readFile, writeFile } from 'node:fs/promises';
import { join, dirname } from 'node:path';
import {
  ensureDir,
  listDirEntries,
  removeFile,
  renamePath,
  statPath,
} from '../fs-safe.mjs';
import { STATE_DIRS } from './layout.mjs';
import {
  MEMORY_PATH,
  REPO_LEDGER_REL,
  TASK_LEDGER_DIR,
} from '../memory/paths.mjs';

/**
 * Minimal seeded header written into a freshly created memory file. Kept tiny
 * on purpose (token-lean) and never written over an existing file.
 * @type {string}
 */
const MEMORY_SEED = '# Memory\n\n> Canonical devmate memory ledger. Managed by you; safe to edit.\n';

/**
 * Content written into `.devmate/.gitignore` when it does not already exist.
 * Ignores transient state and session dirs; explicitly allows MEMORY.md and
 * devmate.config.json so consumers can track the memory ledger and config.
 * @type {string}
 */
const DEVMATE_GITIGNORE_CONTENT = [
  '# Auto-generated by devmate ensureDevmateLayout.',
  '# Ignores transient subdirs; MEMORY.md and devmate.config.json (inside .devmate/) are intentionally tracked.',
  'state/',
  'session/',
  'memory/tasks/',
  '',
  '# Files to track (do not ignore):',
  '!MEMORY.md',
  '!devmate.config.json',
  '',
].join('\n');

/**
 * Transient subdirectories that must always be ignored inside
 * `.devmate/.gitignore`. Used to reconcile a stale gitignore written before a
 * newer entry (e.g. `memory/tasks/`) became required.
 * @type {string[]}
 */
const REQUIRED_GITIGNORE_ENTRIES = ['state/', 'session/', 'memory/tasks/'];

/**
 * @typedef {Object} EnsureLayoutResult
 * @property {string[]} created  Absolute paths created by this call (dirs + memory file).
 * @property {boolean} skipped   True when the layout already existed and nothing was created.
 */

/**
 * Cheap existence check: returns true only if every canonical state directory
 * already exists. Lets the SessionStart hook skip all work on warm sessions
 * (resume/startup) without writing anything.
 *
 * @param {string} repoRoot  Absolute path to the workspace/repo root.
 * @returns {Promise<boolean>}
 */
export async function layoutExists(repoRoot) {
  for (const dir of STATE_DIRS) {
    if (!(await isDir(join(repoRoot, dir)))) {
      return false;
    }
  }
  return true;
}

/**
 * Idempotently seed the `.devmate/` layout under `repoRoot`:
 *  - create each directory in STATE_DIRS with { recursive: true }
 *  - ensure the canonical memory file exists (create with a minimal seed if
 *    missing; NEVER overwrite an existing file)
 *  - write `.devmate/.gitignore` if missing
 *
 * Renamed from ensureCopilotLayout — same contract, new directory root.
 * Safe to call repeatedly — a no-op when everything already exists. Does not
 * touch or alter any existing lazy-mkdir behavior; init is purely additive.
 *
 * @param {string} repoRoot  Absolute path to the workspace/repo root.
 * @returns {Promise<EnsureLayoutResult>}  What was created; skipped=true if nothing to do.
 */
export async function ensureDevmateLayout(repoRoot) {
  const memoryAbs = join(repoRoot, MEMORY_PATH);
  const memoryMissing = !(await pathExists(memoryAbs));
  const gitignoreAbs = join(repoRoot, '.devmate', '.gitignore');
  const gitignoreMissing = !(await pathExists(gitignoreAbs));

  // Reconcile an existing .gitignore up front so warm sessions repair a stale
  // file (e.g. one written before memory/tasks/ became a required ignore).
  const gitignoreReconciled = gitignoreMissing
    ? false
    : await reconcileDevmateGitignore(gitignoreAbs);

  if ((await layoutExists(repoRoot)) && !memoryMissing && !gitignoreMissing) {
    const migrated = await migrateLegacyLedgers(repoRoot);
    if (migrated.length > 0 || gitignoreReconciled) {
      return { created: migrated, skipped: false };
    }
    return { created: [], skipped: true };
  }

  /** @type {string[]} */
  const created = [];

  for (const dir of STATE_DIRS) {
    const abs = join(repoRoot, dir);
    if (!(await isDir(abs))) {
      await ensureDir(abs);
      created.push(abs);
    }
  }

  // Ensure the memory file exists. Never overwrite an existing one.
  if (memoryMissing) {
    await ensureDir(dirname(memoryAbs));
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- 'wx' (O_EXCL) create-only write IS the never-overwrite guarantee for the seeded memory file; facade writers deliberately do not expose open flags. Path is join(repoRoot, MEMORY_PATH).
    await writeFile(memoryAbs, MEMORY_SEED, { flag: 'wx' });
    created.push(memoryAbs);
  }

  // Write nested .gitignore if missing — provides automatic consumer protection.
  if (gitignoreMissing) {
    await ensureDir(dirname(gitignoreAbs));
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- 'wx' (O_EXCL) create-only write IS the never-overwrite guarantee for the seeded .gitignore; facade writers deliberately do not expose open flags. Path is join(repoRoot, '.devmate', '.gitignore').
    await writeFile(gitignoreAbs, DEVMATE_GITIGNORE_CONTENT, { flag: 'wx' });
    created.push(gitignoreAbs);
  }

  const migrated = await migrateLegacyLedgers(repoRoot);
  for (const migratedPath of migrated) {
    created.push(migratedPath);
  }

  return { created, skipped: false };
}

/**
 * Append any missing canonical ignore entries to an existing
 * `.devmate/.gitignore`. Repairs installs whose gitignore predates a newer
 * required entry (e.g. `memory/tasks/`), which the create-only seed path can
 * never fix. Idempotent: writes only when something was appended; a read
 * failure (missing / not a regular file) is a safe no-op.
 * @param {string} gitignoreAbs  Absolute path to `.devmate/.gitignore`.
 * @returns {Promise<boolean>}  True if the file was modified.
 */
async function reconcileDevmateGitignore(gitignoreAbs) {
  /** @type {string} */
  let content;
  try {
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- reconcile read of the repo-local .devmate/.gitignore; path is join(repoRoot, '.devmate', '.gitignore').
    content = await readFile(gitignoreAbs, 'utf8');
  } catch {
    return false;
  }

  const existing = new Set(content.split('\n').map((line) => line.trim()));
  const missing = REQUIRED_GITIGNORE_ENTRIES.filter((entry) => !existing.has(entry));
  if (missing.length === 0) return false;

  const separator = content.length > 0 && !content.endsWith('\n') ? '\n' : '';
  const addition = `${separator}${missing.join('\n')}\n`;
  // eslint-disable-next-line security/detect-non-literal-fs-filename -- reconcile append to the repo-local .devmate/.gitignore; path is join(repoRoot, '.devmate', '.gitignore').
  await writeFile(gitignoreAbs, content + addition);
  return true;
}

/**
 * Move legacy memory ledger files to canonical locations.
 * Silent on no-op; writes one stderr line per actual move/delete.
 * @param {string} repoRoot
 * @returns {Promise<string[]>}
 */
async function migrateLegacyLedgers(repoRoot) {
  /** @type {string[]} */
  const changed = [];

  const legacyRepoLedger = join(repoRoot, '.devmate/state/repo.jsonl');
  const canonicalRepoLedger = join(repoRoot, REPO_LEDGER_REL);
  if (await moveIfPresent(legacyRepoLedger, canonicalRepoLedger)) {
    changed.push(canonicalRepoLedger);
    process.stderr.write(
      JSON.stringify({ event: 'migration.moved', from: legacyRepoLedger, to: canonicalRepoLedger }) + '\n',
    );
  }

  const legacyTaskDir = join(repoRoot, '.devmate/state/tasks');
  const canonicalTaskDir = join(repoRoot, TASK_LEDGER_DIR);
  /** @type {import('node:fs').Dirent[]} */
  let legacyTasks;
  try {
    legacyTasks = await listDirEntries(legacyTaskDir);
  } catch (err) {
    if ((/** @type {NodeJS.ErrnoException} */ (err)).code !== 'ENOENT') {
      throw err;
    }
    legacyTasks = [];
  }

  for (const entry of legacyTasks) {
    if (!entry.isFile() || !entry.name.endsWith('.jsonl')) continue;
    const from = join(legacyTaskDir, entry.name);
    const to = join(repoRoot, canonicalTaskDir, entry.name);
    if (await moveIfPresent(from, to)) {
      changed.push(to);
      process.stderr.write(
        JSON.stringify({ event: 'migration.moved', from, to }) + '\n',
      );
    }
  }

  const legacyFactLedger = join(repoRoot, '.devmate/state/facts.jsonl');
  if (await deleteIfPresent(legacyFactLedger)) {
    changed.push(legacyFactLedger);
    process.stderr.write(
      JSON.stringify({ event: 'migration.deleted', path: legacyFactLedger }) + '\n',
    );
  }

  return changed;
}

/**
 * Move a file if present. Returns true only when the source was moved.
 * @param {string} from
 * @param {string} to
 * @returns {Promise<boolean>}
 */
async function moveIfPresent(from, to) {
  if (!(await pathExists(from))) return false;
  if (await pathExists(to)) return false;
  await ensureDir(dirname(to));
  try {
    await renamePath(from, to);
  } catch (err) {
    const code = (/** @type {NodeJS.ErrnoException} */ (err)).code;
    if (code !== 'EXDEV') throw err;
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- deliberate raw Buffer read (no encoding) so the EXDEV copy fallback preserves bytes exactly; the utf8-only facade wrappers would round-trip through a string. Paths are trusted repo-local migration sources.
    const content = await readFile(from);
    // eslint-disable-next-line security/detect-non-literal-fs-filename -- deliberate raw write of the Buffer read above (byte-exact EXDEV copy); facade writers are utf8-string-only. Paths are trusted repo-local migration targets.
    await writeFile(to, content);
    await removeFile(from);
  }
  return true;
}

/**
 * Delete a file if present.
 * @param {string} filePath
 * @returns {Promise<boolean>}
 */
async function deleteIfPresent(filePath) {
  try {
    await removeFile(filePath);
    return true;
  } catch (err) {
    const code = (/** @type {NodeJS.ErrnoException} */ (err)).code;
    if (code === 'ENOENT') return false;
    throw err;
  }
}

/**
 * True if `p` exists and is a directory.
 * @param {string} p  Absolute path.
 * @returns {Promise<boolean>}
 */
async function isDir(p) {
  try {
    const s = await statPath(p);
    return s.isDirectory();
  } catch {
    return false;
  }
}

/**
 * True if `p` exists (any type).
 * @param {string} p  Absolute path.
 * @returns {Promise<boolean>}
 */
async function pathExists(p) {
  try {
    await statPath(p);
    return true;
  } catch {
    return false;
  }
}
