// @ts-check
import { dirname, join } from "node:path";
import { pathToFileURL } from "node:url";
import {
  buildConfigFromPersonas,
  initConfig,
} from "../lib/config/init-config.mjs";
import { assertNodeVersion } from "../lib/env-guard.mjs";
import {
  ensureDirSync,
  pathExists,
  readTextFileSync,
  writeTextFileSync,
} from "../lib/fs-safe.mjs";
import { parseJsonSafe } from "../lib/json-io.mjs";
import { ensureDevmateLayout } from "../lib/init/devmate-init.mjs";
import { inferPersonas } from "../lib/init/infer-personas.mjs";
import { inferVerificationChecks } from "../lib/init/infer-verification.mjs";
import {
  detectMultiRootMode,
  fallbackReposOf,
  formatContractSkewNudge,
  formatFallbackNudge,
  formatMultiRootGuardFailure,
  validateMultiRootInit,
} from "../lib/init/multi-root-init.mjs";
import { readSessionHandshake } from "../lib/init/session-handshake.mjs";
import { loadDevmateConfig } from "../lib/config/devmate-config.mjs";
import { CONTRACT_VERSION } from "../lib/config/contract-version.mjs";
import { resolveRepoRoot } from "../lib/init/repo-root.mjs";
import { ensureDevmatePromptFile } from "../lib/init/scaffold-prompt.mjs";
import { scanRepoSignals } from "../lib/init/scan-repo-signals.mjs";
import { scanVerificationSignals } from "../lib/init/scan-verification-signals.mjs";

/** @typedef {import('../lib/types.mjs').DevmateConfig} DevmateConfig */

/** Draft artifact paths (relative to repo root), documented in the skill. */
const PROPOSAL_PATH = ".devmate/state/init-proposal.json";
const EVIDENCE_PATH = ".devmate/state/init-evidence.json";

/**
 * `devmate init` entrypoint — scaffolds a starter devmate.config.json declaring
 * stack personas and their editable / off-limits globs. This is the file the
 * gate-guard fail-safe blocks on when it is missing or invalid.
 *
 * Flags:
 *   --infer            Infer a proposal from the repo structure instead of the
 *                      static starter config. Without --write this GENERATES a
 *                      deterministic, evidence-grounded proposal (personas +
 *                      verification checks) at .devmate/state/init-proposal.json
 *                      plus an evidence artifact, prints a digest, and writes no
 *                      real config (propose -> review/enrich -> write).
 *   --write            With --infer, APPLY the reviewed proposal — honoring any
 *                      human edits / LLM enrichment on disk, recomputing the
 *                      floor only when no proposal exists. Same never-overwrite /
 *                      --force safety as the static path.
 *   --force            Overwrite an existing config.
 *   --path <file>      Target path (defaults to devmate.config.json).
 *
 * @param {string[]} args  CLI args (without node/script).
 * @param {{ out?: (s: string) => void, err?: (s: string) => void }} [io]
 *   Injectable writers (default stdout/stderr). Tests pass collectors so they
 *   never have to monkeypatch the global streams.
 * @returns {Promise<number>} exit code (0 ok, 1 on failure)
 */
export async function main(args, io = {}) {
  const out = io.out ?? ((s) => process.stdout.write(s));
  const err = io.err ?? ((s) => process.stderr.write(s));
  const force = args.includes("--force");
  const infer = args.includes("--infer");
  const write = args.includes("--write");

  let configPath;
  const pathIdx = args.indexOf("--path");
  const pathVal = args.at(pathIdx + 1);
  if (pathIdx !== -1 && pathVal) {
    configPath = pathVal;
  }

  // B6: multi-root guard — must run before any other logic so the single-root
  // init flow never touches a config generated by monoroot.
  const repoRootForGuard = await resolveRepoRoot(process.cwd());
  if (await detectMultiRootMode(repoRootForGuard)) {
    const result = await validateMultiRootInit(repoRootForGuard);
    if (!result.ok) {
      err(`${formatMultiRootGuardFailure(result, { repoRoot: repoRootForGuard })}\n`);
      return 1;
    }
    // Consume the util's session.json handshake for the authoritative primary,
    // and read the merged config to surface a non-blocking fallback-scoping nudge.
    const handshake = await readSessionHandshake(repoRootForGuard);
    const cfg = loadDevmateConfig(
      join(repoRootForGuard, ".devmate/devmate.config.json"),
      repoRootForGuard,
    );
    const fallbackRepos = cfg.ok ? fallbackReposOf(cfg.config) : [];

    const lines = [
      `devmate: multi-root workspace detected. Config was generated by ` +
        `monoroot. Validation passed.` +
        (handshake ? ` Primary repo: ${handshake.primary}.` : ""),
    ];
    if (fallbackRepos.length > 0) {
      lines.push(formatFallbackNudge(fallbackRepos));
    }
    // Contract-version skew nudge (fail-open): only when the producer stamped
    // a numeric contractVersion that differs from this build's pinned version.
    // An unstamped config (older producer) or an unreadable config never nudges.
    if (cfg.ok) {
      const stamped = /** @type {Record<string, unknown>} */ (
        /** @type {unknown} */ (cfg.config)
      )["contractVersion"];
      if (typeof stamped === "number" && stamped !== CONTRACT_VERSION) {
        lines.push(formatContractSkewNudge(stamped, CONTRACT_VERSION));
      }
    }
    out(lines.join("\n") + "\n");
    return 0; // STOP — do not proceed to single-root init flow.
  }

  // Inference path (#142): scan repo signals, infer personas, propose a config.
  if (infer) {
    return runInfer({ configPath, force, write }, { out, err });
  }

  // Static starter path (original behavior): always writes.
  // Bug 2: resolve repoRoot so initConfig writes to the project root.
  const repoRoot = repoRootForGuard;
  const result = initConfig({ configPath, force, repoRoot });
  if (!result.ok) {
    err(`[devmate init] ${result.error}\n`);
    return 1;
  }

  // Bug 3: seed the .devmate/ layout and .gitignore after a successful write.
  try {
    await ensureDevmateLayout(repoRoot);
  } catch (layoutErr) {
    err(`[devmate init] Warning: layout seeding failed — ${layoutErr instanceof Error ? layoutErr.message : String(layoutErr)}\n`);
  }

  out(
    `[devmate init] Wrote starter config to ${result.path}. ` +
      `Edit the personas and globs to match your stack, then commit it.\n`,
  );
  await scaffoldPromptFile(repoRoot, out, err);
  return 0;
}

/**
 * Scaffold the `/devmate` prompt file into the repo and report the outcome.
 * Best-effort: a scaffold failure warns but never fails init, because the config
 * write (the primary action) has already succeeded by the time this runs. The
 * scaffolder is create-only, so an existing (possibly customised) prompt file is
 * left untouched and silently skipped.
 *
 * @param {string} repoRoot  Absolute path to the resolved repo root.
 * @param {(s: string) => void} out
 * @param {(s: string) => void} err
 * @returns {Promise<void>}
 */
async function scaffoldPromptFile(repoRoot, out, err) {
  try {
    const scaffold = await ensureDevmatePromptFile(repoRoot);
    if (scaffold.created) {
      out(
        `[devmate init] Scaffolded the /devmate slash command to ${scaffold.created}. ` +
          `Type /devmate <task> in Copilot Chat to run the orchestrator directly.\n`,
      );
    }
  } catch (scaffoldErr) {
    err(
      `[devmate init] Warning: /devmate prompt scaffold failed — ` +
        `${scaffoldErr instanceof Error ? scaffoldErr.message : String(scaffoldErr)}\n`,
    );
  }
}

/**
 * Inference flow dispatcher. Without --write it GENERATES a deterministic,
 * evidence-grounded proposal (+ an evidence artifact) for the agent/user to
 * review and enrich; with --write it APPLIES the reviewed proposal.
 *
 * @param {{ configPath?: string, force: boolean, write: boolean }} opts
 * @param {{ out: (s: string) => void, err: (s: string) => void }} io
 * @returns {Promise<number>}
 */
async function runInfer(opts, io) {
  return opts.write ? runWrite(opts, io) : runGenerate(opts, io);
}

/**
 * Build the deterministic proposal floor: scan repo signals + verification
 * evidence, infer grounded personas + verification checks. Pure w.r.t. the tree
 * (same repo ⇒ same proposal). Returns the config plus the raw scan artifacts so
 * the caller can also persist the evidence.
 *
 * @param {string} repoRoot
 * @returns {Promise<{ config: DevmateConfig, signals: import('../lib/init/scan-repo-signals.mjs').RepoSignals, candidates: import('../lib/types.mjs').VerificationCandidate[] }>}
 */
async function buildProposedConfig(repoRoot) {
  const signals = await scanRepoSignals(repoRoot);
  const candidates = await scanVerificationSignals(repoRoot);
  const personas = inferPersonas(signals);
  const checks = inferVerificationChecks(candidates);
  return { config: buildConfigFromPersonas(personas, { checks }), signals, candidates };
}

/**
 * GENERATE: write the proposal + evidence drafts under .devmate/state/ and print
 * a digest only (TCM-9 — never the file contents). Writes no real config.
 *
 * @param {{ configPath?: string, force: boolean, write: boolean }} opts
 * @param {{ out: (s: string) => void, err: (s: string) => void }} io
 * @returns {Promise<number>}
 */
async function runGenerate(opts, io) {
  const repoRoot = await resolveRepoRoot(process.cwd());
  const { config, signals, candidates } = await buildProposedConfig(repoRoot);

  writeJsonFile(join(repoRoot, PROPOSAL_PATH), config);
  writeJsonFile(join(repoRoot, EVIDENCE_PATH), { schemaVersion: 1, candidates, layout: signals });

  const personaNames = config.personas.map((p) => p.persona).join(", ");
  const checkIds = (config.verification?.checks ?? []).map((c) => c.id);
  const checkList = checkIds.length > 0 ? `: ${checkIds.join(", ")}` : "";
  io.out(
    `[devmate init] proposal: ${config.personas.length} persona(s): ${personaNames}; ` +
      `${checkIds.length} verification check(s)${checkList}\n`,
  );
  io.out(
    `[devmate init] wrote ${PROPOSAL_PATH} and ${EVIDENCE_PATH} (${candidates.length} candidate(s) scanned)\n`,
  );
  io.out(
    `[devmate init] review/enrich the proposal, then write it: node scripts/init.mjs --infer --write\n`,
  );
  return 0;
}

/**
 * APPLY: persist the REVIEWED proposal (honoring human edits / LLM enrichment).
 * Falls back to a fresh deterministic floor only when no proposal exists on
 * disk (standalone `--infer --write`). Same validation + never-overwrite safety
 * as the static path — the write is re-validated by initConfig.
 *
 * @param {{ configPath?: string, force: boolean, write: boolean }} opts
 * @param {{ out: (s: string) => void, err: (s: string) => void }} io
 * @returns {Promise<number>}
 */
async function runWrite(opts, io) {
  const repoRoot = await resolveRepoRoot(process.cwd());
  const reviewed = readReviewedProposal(repoRoot);
  const proposed = reviewed ?? (await buildProposedConfig(repoRoot)).config;

  const result = initConfig({
    configPath: opts.configPath,
    force: opts.force,
    config: proposed,
    repoRoot,
  });
  if (!result.ok) {
    io.err(`[devmate init] ${result.error}\n`);
    return 1;
  }

  try {
    await ensureDevmateLayout(repoRoot);
  } catch (layoutErr) {
    io.err(`[devmate init] Warning: layout seeding failed — ${layoutErr instanceof Error ? layoutErr.message : String(layoutErr)}\n`);
  }

  io.out(
    `[devmate init] Wrote ${reviewed ? "reviewed" : "inferred"} config to ${result.path}. ` +
      `Review the personas and globs (especially off-limits), then commit it.\n`,
  );
  await scaffoldPromptFile(repoRoot, io.out, io.err);
  return 0;
}

/**
 * Read the reviewed proposal draft from disk, or null when absent/malformed
 * (the write path then recomputes the deterministic floor).
 * @param {string} repoRoot
 * @returns {DevmateConfig|null}
 */
function readReviewedProposal(repoRoot) {
  const proposalAbs = join(repoRoot, PROPOSAL_PATH);
  if (!pathExists(proposalAbs)) return null;
  try {
    const parsed = parseJsonSafe(readTextFileSync(proposalAbs));
    if (parsed !== null && typeof parsed === "object" && !Array.isArray(parsed)) {
      return /** @type {DevmateConfig} */ (parsed);
    }
  } catch {
    // Fall through to recompute — the reviewed file is unreadable/corrupt.
  }
  return null;
}

/**
 * Write a JSON draft artifact, pretty-printed so a human/agent can edit it.
 * @param {string} absPath
 * @param {unknown} data
 * @returns {void}
 */
function writeJsonFile(absPath, data) {
  ensureDirSync(dirname(absPath));
  writeTextFileSync(absPath, JSON.stringify(data, null, 2) + "\n");
}

// Only run when executed directly, not when imported by tests.
// Bug 1: pathToFileURL normalises backslashes, drive-letter casing, and the
// triple-slash prefix on Windows so the comparison is always canonical.
if (import.meta.url === pathToFileURL(process.argv[1]).href) {
  assertNodeVersion(24);
  main(process.argv.slice(2)).then((code) => process.exit(code));
}
