// @ts-check

import assert from 'node:assert/strict';
import { test, describe } from 'node:test';
import { mkdtempSync, writeFileSync, readFileSync, rmSync, mkdirSync } from 'node:fs';
import { tmpdir } from 'node:os';
import { resolve } from 'node:path';
import {
  parseAgentFile,
  renderCliAgent,
  main,
  DEFAULT_AGENTS,
} from '../../scripts/generate-cli-agents.mjs';
import { main as check } from '../../scripts/check-generated-cli-agents.mjs';

// ============================================================================
// Unit tests: frontmatter parsing + CLI rendering (the "share contents" core)
// ============================================================================

test('parseAgentFile / extracts scalar frontmatter and body verbatim', () => {
  const text = [
    '---',
    "name: planner",
    'description: Makes plans.',
    'tools: ["read"]',
    'user-invocable: false',
    'model: Sonnet',
    '---',
    '',
    '# Planner Agent',
    '',
    'Role body line.',
  ].join('\n');
  const parsed = parseAgentFile(text);
  assert.ok(parsed, 'parsed should be non-null');
  assert.equal(parsed.frontmatter.name, 'planner');
  assert.equal(parsed.frontmatter.description, 'Makes plans.');
  assert.equal(parsed.frontmatter.model, 'Sonnet');
  assert.equal(parsed.frontmatter.raw.includes('user-invocable'), true);
  assert.ok(parsed.body.includes('# Planner Agent'));
  assert.ok(parsed.body.includes('Role body line.'));
});

test('parseAgentFile / picks the first model from an array fallback', () => {
  const text = [
    '---',
    "name: rubber-duck",
    "model: ['Claude Opus 4.8 (copilot)', 'Claude Sonnet 5 (copilot)']",
    '---',
    '',
    'body',
  ].join('\n');
  const parsed = parseAgentFile(text);
  assert.ok(parsed);
  assert.equal(parsed.frontmatter.model, 'Claude Opus 4.8 (copilot)');
});

test('parseAgentFile / returns null without a closing fence', () => {
  const text = '---\nname: x\ndescription: y\n';
  assert.equal(parseAgentFile(text), null);
});

test('renderCliAgent / emits normalized frontmatter, generated header, verbatim body', () => {
  const frontmatter = {
    name: 'planner',
    description: 'Makes plans.',
    model: 'Sonnet',
    raw: 'name: planner\nmodel: Sonnet',
  };
  const body = '\n\n# Planner Agent\n\nRole body line.\n';
  const out = renderCliAgent(frontmatter, body, 'agents/planner.agent.md');
  // Frontmatter is first (line 1 = ---) so Copilot CLI discovery works; the
  // generated note lives as YAML comments inside the block.
  assert.ok(out.startsWith('---\n# GENERATED by scripts/generate-cli-agents.mjs'));
  assert.ok(out.includes('# Source of truth: agents/planner.agent.md'));
  // Normalized frontmatter only keeps name/description/model.
  assert.ok(out.includes('name: planner'));
  assert.ok(out.includes('description: Makes plans.'));
  assert.ok(out.includes('model: Sonnet'));
  assert.ok(!out.includes('user-invocable'));
  // Body is shared verbatim.
  assert.ok(out.includes('# Planner Agent'));
  assert.ok(out.includes('Role body line.'));
});

// ============================================================================
// Integration: generator + drift check against a tmpdir repo
// ============================================================================

describe('generate + check (tmpdir repo)', () => {
  /** @returns {string} */
  function setupTmpRepo() {
    const root = mkdtempSync(resolve(tmpdir(), 'devmate-cli-agents-'));
    mkdirSync(resolve(root, 'agents'), { recursive: true });
    const planner =
      '---\nname: planner\ndescription: Plans.\nuser-invocable: false\nmodel: Sonnet\n---\n\n# Planner Agent\n\nbody.\n';
    const duck =
      "---\nname: rubber-duck\ndescription: Ducks.\nmodel: ['Opus', 'Sonnet']\n---\n\n# Rubber-Duck Agent\n\nbody.\n";
    writeFileSync(resolve(root, 'agents/planner.agent.md'), planner);
    writeFileSync(resolve(root, 'agents/rubber-duck.agent.md'), duck);
    return root;
  }

  test('main / writes both CLI agents; second run is a no-op', async () => {
    const root = setupTmpRepo();
    const agents = DEFAULT_AGENTS;
    let code = await main([], { agents, rootOverride: root });
    assert.equal(code, 0);
    const plannerOut = readFileSync(resolve(root, '.github/agents/planner.md'), 'utf8');
    assert.ok(plannerOut.includes('name: planner'));
    assert.ok(plannerOut.includes('model: Sonnet'));
    const duckOut = readFileSync(resolve(root, '.github/agents/rubber-duck.md'), 'utf8');
    assert.ok(duckOut.includes('model: Opus'));

    // Idempotent: no rewrite on the second run.
    code = await main([], { agents, rootOverride: root });
    assert.equal(code, 0);

    // Drift check passes immediately after generation.
    code = await check([], { agents, rootOverride: root });
    assert.equal(code, 0);
    rmSync(root, { recursive: true, force: true });
  });

  test('check / detects a stale target after manual edit', async () => {
    const root = setupTmpRepo();
    await main([], { agents: DEFAULT_AGENTS, rootOverride: root });
    const target = resolve(root, '.github/agents/planner.md');
    writeFileSync(target, 'tampered\n');
    const code = await check([], { agents: DEFAULT_AGENTS, rootOverride: root });
    assert.equal(code, 1);
    rmSync(root, { recursive: true, force: true });
  });

  test('check / detects a missing target', async () => {
    const root = setupTmpRepo();
    // Never generate; targets are missing.
    const code = await check([], { agents: DEFAULT_AGENTS, rootOverride: root });
    assert.equal(code, 1);
    rmSync(root, { recursive: true, force: true });
  });
});
