#!/usr/bin/env bash
# Post the finalized plan (and a paste-able devmate handoff prompt) as a
# comment on the triggering issue. Posts both when the plan grill approved
# (status: Approved) and when it did not (status: Needs human review + the
# grill's open blockers). Minimizes prior devmate story-plan comments
# (detected via marker) so the thread stays readable on reruns.
#
# Env:
#   GH_TOKEN, ISSUE_NUMBER, REPO
#   STORY_PLAN_MARKER - from lib.sh
# Inputs: plan.md, verdict.txt, critique.md (optional)
set -euo pipefail
source "$(dirname "$0")/lib.sh"

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${ISSUE_NUMBER:?ISSUE_NUMBER is required}"
: "${REPO:?REPO is required}"

if [ ! -s plan.md ]; then
  echo "post-comment: plan.md is empty; nothing to post." >&2
  exit 1
fi

owner="${REPO%/*}"
name="${REPO#*/}"

# 1. Minimize prior devmate story-plan comments (more reliable than author filtering).
ids="$(gh api graphql \
  -f query='
    query($owner:String!, $name:String!, $number:Int!) {
      repository(owner:$owner, name:$name) {
        issue(number:$number) {
          comments(first:100) {
            nodes { id body isMinimized }
          }
        }
      }
    }' \
  -F owner="$owner" -F name="$name" -F number="$ISSUE_NUMBER" \
  --jq ".data.repository.issue.comments.nodes[] | select(.isMinimized == false) | select(.body | contains(\"$STORY_PLAN_MARKER\")) | .id" 2>/dev/null || true)"
if [ -n "$ids" ]; then
  for id in $ids; do
    echo "post-comment: minimizing prior plan comment $id" >&2
    gh api graphql \
      -f query='
        mutation($id:ID!) {
          minimizeComment(input:{classifier:OUTDATED, subjectId:$id}) {
            minimizedComment { isMinimized minimizedReason }
          }
        }' \
      -F id="$id" >/dev/null 2>&1 || true
  done
fi

# 2. Read the grill verdict and assemble the comment.
verdict="$(cat verdict.txt 2>/dev/null || true)"
case "$verdict" in
  NEEDS_REVIEW) status="Needs human review — the plan grill did not approve.";;
  APPROVE_PLAN|"") status="Approved by plan grill.";;
  *) status="Approved by plan grill.";;
esac

{
  printf '%s\n' "$STORY_PLAN_MARKER"
  echo
  echo "# Story Planner: Backlog Grooming Plan"
  echo
  echo "## Status"
  echo
  echo "$status"
  echo
  echo "> Auto-generated by the devmate story-planner agent. This is a"
  echo "> backlog-grooming plan, not a final spec — review before implementing."
  echo
  echo "## Plan"
  echo
  cat plan.md
  if [ "$verdict" = "NEEDS_REVIEW" ] && [ -s critique.md ]; then
    echo
    echo "## Open blockers (from the plan grill)"
    echo
    cat critique.md
  elif [ -s critique.md ]; then
    echo
    echo "<details><summary>Plan grill critique</summary>"
    echo
    cat critique.md
    echo
    echo "</details>"
  fi
  echo
  echo "## Paste into devmate (GitHub Copilot Chat)"
  echo
  echo '```text'
  printf 'Use this comment as backlog-grooming context, not as a final spec.\n\n'
  printf 'Re-read issue #%s and rediscover the current code before implementing —\n' "$ISSUE_NUMBER"
  printf 'the codebase may have changed since this plan was generated.\n'
  printf 'Resolve or validate all [UNVERIFIED] items with me first.\n'
  printf 'Then produce the detailed implementation spec and TDD plan in devmate.\n'
  printf 'Do not treat this CI-generated plan as authoritative if it conflicts with\n'
  printf 'the code.\n'
  echo '```'
} > comment.md

# 3. Post the comment.
gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body-file comment.md
echo "post-comment: posted plan to $REPO#$ISSUE_NUMBER" >&2
