#!/usr/bin/env bash
# Post the finalized plan as a comment on the triggering issue.
# Only posts when verdict is APPROVE_PLAN. Minimizes prior devmate story-plan
# comments (detected via marker) so the thread stays readable on reruns.
#
# Env:
#   GH_TOKEN, ISSUE_NUMBER, REPO
#   STORY_PLAN_MARKER - from lib.sh
# Inputs: plan.md, critique.md (optional)
set -euo pipefail
source "$(dirname "$0")/lib.sh"

: "${GH_TOKEN:?GH_TOKEN is required}"
: "${ISSUE_NUMBER:?ISSUE_NUMBER is required}"
: "${REPO:?REPO is required}"

if [ ! -s plan.md ]; then
  echo "post-comment: plan.md is empty; nothing to post." >&2
  exit 1
fi

owner="${REPO%/*}"
name="${REPO#*/}"

# 1. Minimize prior devmate story-plan comments (more reliable than author filtering).
ids="$(gh api graphql \
  -f query='
    query($owner:String!, $name:String!, $number:Int!) {
      repository(owner:$owner, name:$name) {
        issue(number:$number) {
          comments(first:100) {
            nodes { id body isMinimized }
          }
        }
      }
    }' \
  -F owner="$owner" -F name="$name" -F number="$ISSUE_NUMBER" \
  --jq ".data.repository.issue.comments.nodes[] | select(.isMinimized == false) | select(.body | contains(\"$STORY_PLAN_MARKER\")) | .id" 2>/dev/null || true)"
if [ -n "$ids" ]; then
  for id in $ids; do
    echo "post-comment: minimizing prior plan comment $id" >&2
    gh api graphql \
      -f query='
        mutation($id:ID!) {
          minimizeComment(input:{classifier:OUTDATED, subjectId:$id}) {
            minimizedComment { isMinimized minimizedReason }
          }
        }' \
      -F id="$id" >/dev/null 2>&1 || true
  done
fi

# 2. Assemble the comment: hidden marker + plan + (optional) critique summary.
{
  printf '%s\n' "$STORY_PLAN_MARKER"
  echo
  echo "## Story Plan"
  echo
  echo "> Auto-generated by the devmate story-planner agent. Rubber-ducked before posting. Review before implementing."
  echo
  cat plan.md
  if [ -s critique.md ]; then
    echo
    echo "<details><summary>Rubber-duck critique</summary>"
    echo
    cat critique.md
    echo
    echo "</details>"
  fi
} > comment.md

# 3. Post the comment.
gh issue comment "$ISSUE_NUMBER" --repo "$REPO" --body-file comment.md
echo "post-comment: posted plan to $REPO#$ISSUE_NUMBER" >&2
